### ISSUE TITLE
ION Scanner and Harvester finishing

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#106]
Textures for both and crafting! Look at #97

**Comment by sammko** [comment]
I will do the crafting, also will have to modify the crafting for ION Tunneler and the ION Forge. They should all contain the ION Core which will be a new crafting item. (maybe will have other uses)

**Comment by hunterboerner** [comment]
Crafting is done. You can change it if you want. All I need is the harvester texture. Remember, the harvester  is meant to be fairly cheap because you need a LOT.
