### ISSUE TITLE
@sammko, is this needed? The textures are being controlled elsewhere. [qc_common/quantumcraft/core/Loader.java]

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#114]
**filename** : qc_common/quantumcraft/core/Loader.java
**line #** : 232
**tag** : bug
**md5** : f5affdbb39c0eff0524ee229f6b85862

```
               // [bug] - @sammko, is this needed? The textures are being controlled elsewhere.
               .setUnlocalizedName(Config.NameBlockIOH).setTextureName(Config.getTextureName(Config.NameBlockIOH));
       LanguageRegistry.addName(BlockIONHarvester, "ION Harvester");
       GameRegistry.registerBlock(BlockIONHarvester, Config.NameBlockIOH);
           if (Config.beta.getBoolean(false)) {
           BlockQCapacitor = (BlockQCapacitor) new BlockQCapacitor(Config.BlockQCPID).setCreativeTab(tabQuantumCraft)
                   .setUnlocalizedName(Config.NameBlockQCP).setTextureName(Config.getTextureName(Config.NameBlockQCP));
               BlockQDislocator =
                   (BlockQDislocator) new BlockQDislocator(Config.BlockQDSID).setCreativeTab(tabQuantumCraft)
                           .setUnlocalizedName(Config.NameBlockQDS)
                           .setTextureName(Config.getTextureName(Config.NameBlockQDS));
           LanguageRegistry.addName(BlockQDislocator, "Quantum Dislocator");
           GameRegistry.registerBlock(BlockQDislocator, Config.NameBlockQDS);
               BlockQEnergySucker =
```

**Comment by sammko** [comment]
which part of it? .setTextureName(Config.getTextureName(Config.NameBlockIOH));

**Comment by hunterboerner** [comment]
Yes. the texture

On Fri, Nov 22, 2013 at 11:02 AM, sammko notifications@github.com wrote:

> which part of it?
> .setTextureName(Config.getTextureName(Config.NameBlockIOH));
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HeisenBugDev/QuantumCraft/issues/114#issuecomment-29089567
> .

## 

## Theron Boerner

**Comment by sammko** [comment]
theoretically, we do not need that there. but only for the machines

**Comment by hunterboerner** [comment]
ok

On Fri, Nov 22, 2013 at 11:07 AM, sammko notifications@github.com wrote:

> theoretically, we do not need that there. but only for the machines
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HeisenBugDev/QuantumCraft/issues/114#issuecomment-29090072
> .

## 

## Theron Boerner
