### ISSUE TITLE
Quantum Dislocator

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#119]
This is now going to be the main ticket for the Dislocator. Having a bajillion random ones is annoying!

So...

http://www.youtube.com/watch?v=iC7jdQ5skSA
take a look.

When 2 chests are linked with the dislocator, one of the chests looses its texture. Also, the chest with no texture is no longer a valid inventory.
EDIT: Its not really a problem w/ the texture, but the TESR doesnt like having the same TE in 2 places

example: http://puu.sh/3O6ct.jpg

```
```

after breaking the dislocator it doesnt modify either of the block, therefore you have double of what you had.

```
```

java.lang.ArrayIndexOutOfBoundsException: 6
at buildcraft.transport.TileGenericPipe.isPipeConnected(TileGenericPipe.java:491)

```
```

java.lang.NullPointerException
at mods.quantumcraft.machine.abstractmachines.TileEnergySink.writeToNBT(TileEnergySink.java:72)
at mods.quantumcraft.machine.TileQEInjector.writeToNBT(TileQEInjector.java:226)

**Comment by sammko** [comment]
i have an idea what could be done to fix some of this, but doing it will break a ton of other stuff
