### ISSUE TITLE
Waiting on a merge change

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#120]
For those "waiting on a merge" @LordFokas mostly. You don't create an issue! You create a pull request. You CAN do those within a repo and it does NOT have to be between forks. It's easy, github will say: you have pushed these branches, PR? You click that and do the buttons. We will then get it. NO MORE LABELS.

@sammko 
@wtg62

**Comment by LordFokas** [comment]
Yes, I do that within my own repos.
I was writing code to help you out, and left _all_ the code management to you (the code's there, do whatever you want with it) mainly because you freak out over irrelevant stuff, just like above.
