### ISSUE TITLE
Redstone controls in GUI

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#138]
Some controls for redstone in gui. Either run when signal, run when no signal, or disable.

**Comment by sammko** [comment]
Fixed in 70647ab5989cd3dff03830711cb95371bb0e4bf6 (ignore the logs in that commit, i removed them)

**Comment by hunterboerner** [comment]
Added a ton of bugs and does not work on all machines. Reverting...
