### ISSUE TITLE
Refactor GUIs

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#153]
GUI code is still a mess. There is TONS of duplication everywhere. Anything that is duplicated should be moved to the base class. Sammko, can you please stop copy-pasting stuff... :angry: :rage:

**Comment by sammko** [comment]
I can consider copy pasting stuff

**Comment by sammko** [comment]
Consider stopping that is

**Comment by hunterboerner** [comment]
Yeah... copy-paste = bad. Don't do it. Plz can I haz refaktor?

**Comment by hunterboerner** [comment]
Beginning work on this myself. What am I getting into :worried:
