### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#154]
Things just aren't balanced and we need to fix that. This ticket will be used for figuring out the ratios, quantities, and other stuff that either makes the mod too hard or too OP (Over Powered for the n00bs).

TODO:
- ~~Tools use 50 power per block mined and make energy buffer 10x~~
## Power Conversion

Other mods power conversions:

10 RF => 1 MJ (BC)

Let's start with the basics. The system depends on power and a proper balance of it is important. Let's base this around smelting, so the ION Forge. Since the ION Forge's only buff is speed, we're going to bump it up a little bit. Pulling in data from other mods, here's what we get: (PC is PowerConverters)

**Thermal Expansion**
Normal Smelting: 1600 RF (860000 PC)

**IC2**
Electric Furnace: 390EU (702000)
Induction: 6000 no heat. 208 max heat

**Universal Electricity**
Electric Furnace: 10kw (100,000)

**Vanilla**
1 Coal: 8 uses

If we look at PowerCrystals' PowerConverters we get these ratios:

_PC:Mod ratio_

UE (watt): 10:1
IC2: 1800:1
BC: 5375:1
RC: 875:1 millibucket

We first see that UE is waaaaay off in the PC conversions so we're going to ignore that. This puts us between 702k and 860k. We're going to go for 800k per smelted block. I decided to put it at **128 QEU per block** meaning... 6250 PC units.
**all numbers are aprox. I changed it around a LOT and was lazy**
The Quantonium Ore gets spawned in 1 vein per chunk each 10 big meaning the **ION Scanner which will use 4 per tick** and say we have 20 harvesters which will use **64 QEU per block** mined would take 600 ticks to scan the area and 80000 ticks to mine about 8000 ores which would use 512000 QEU on the Harvesters, giving us 834200 QEU for the entire run. To _get that energy back_ you have to turn it into crystals using a furnace, which uses 128 QEU per item which the Quantonium Ore gives you about 3 drops per block and you got 10 blocks so 60 per chunk and about 16 chunks so 480 items of Raw Quantonium giving us 61440 QEU for all the Quantonium smelting which in total gives us 637680 QEU and still over 7500 blocks still to process so I'm just going to add a big number for that: 600000 QEU (considering there will be a lot of item drops and we want to have energy loss so it isn't infinite power). So in total, it will be about 1357680 QEU. With that in mind, we got about 480 Quantonium Crystals giving us **1100 QEU per crystal**. That also means that one crystal is about 12790 RF and you can generate that in about 10 seconds with a magmatic engine and 1 bucket of lava.

Summary: a basic scanner system will pay in power for about 1/3 of the power cost.

**Comment by hunterboerner** [comment]
@sammko, the Quantum Fiber Wire recipes require an excessive amount of crystals and unbioxenium. Should we go for the TE way of things rather than IC2? Have a machine do something to make and have easy recipes?

**Comment by sammko** [comment]
You mean like liquid redstone injection from TE? but customized? like liquid quantonium? that could be awesome

**Comment by hunterboerner** [comment]
@sammko, let's not do exactly what they do.

**Comment by sammko** [comment]
Yeah thats true
