### ISSUE TITLE
GUI Hover visual bug

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#159]
When hovering over the power bar, this happens in NEI. VERY minor and may not be fixable so don't work on this one first :pizza: 

![image](https://f.cloud.github.com/assets/1314119/1802826/2636e50c-6c0b-11e3-9eac-e20128886f55.png)

**Comment by sammko** [comment]
Yeah i know, i noticed that BC has ( or used to have ) this issue too. not sure if they fixed it

**Comment by hunterboerner** [comment]
Teh gogoles?
