### ISSUE TITLE
Phase-shifting mobs

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#164]
When you start doing weird things, things get even weirder. One minute a pig, then a creeper, but when you check to see if you're going crazy, it's a pig...

**Comment by sammko** [comment]
:D awesome idea.. how would we go about implementing this? I've always wondered how other mods implement stuff like this, cause you need a method that ticks, and you get that only in blocks, TEs and entities. Or is there a way maybe w/ @ForgeSubscribe to make a method get called on a gametick?

**Comment by sammko** [comment]
Or maybe we add a static bool somewhere, and in updateEntity in BlockMachine we could check for that bool and if its false, the TE will call a method somewhere on every tick and will set the bool to true. When you break the TE it will set the flag to false only if it was set to true by that TE, and then some other TE will start calling it and set the flag to true.   Did that make sense?

**Comment by sammko** [comment]
That means if you have no QC machines it wont be doing weirdness which is cool, cause there will be nothing causing fluctuations in the quantum field :D
