### ISSUE TITLE
Quantum Materializer		 		

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#18]
Convert Quantum Energy back to somthing like UU-Matter.

**Comment by hunterboerner** [comment]
**requires IC2 so we postponed it**

**Comment by sammko** [comment]
0.6 Is gonna require IC2.
EDIT: NVM

**Comment by hunterboerner** [comment]
@sammko, do you think we could do this in some other manner than requiring IC2.
