### ISSUE TITLE
(Quantum?) Fusion Reactor		 		

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#20]
Generate Quantum Energy from (unknown?) materials. (still not planned well, LOW PRIORITY)

**Comment by hunterboerner** [comment]
Nope, too old

**Comment by sammko** [comment]
what is your problem? I thought i was planning the mod's features

**Comment by sammko** [comment]
i still got ideas for this

**Comment by hunterboerner** [comment]
If you have ideas, you should put them in here rather than letting it sit forever

**Comment by sammko** [comment]
I will when i make it more clear, it is still not planned well as the OP stated, and maybe asking if you can close feature issues that are little bit older may help for your in-team reputation -.-
