### ISSUE TITLE
Quantum Capacitor

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#22]
Used to store Quantum Energy

**Comment by hunterboerner** [comment]
This is a block!

**Comment by sammko** [comment]
moving to 1.0, our current energy network doesnt support this.

**Comment by hunterboerner** [comment]
It may be possible. The block would always require energy unless full or something else needs it, probably not though.

**Comment by sammko** [comment]
nope. the problem is the block would request power from itself. we need to get fokas to fix that.

**Comment by hunterboerner** [comment]
@LordFokas  :+1:

**Comment by LordFokas** [comment]
It requires reworking a good part of the network, but shouldn't be anything serious.
I'll be available for it as soon as I stop being pissed at BC for forcing people to lose power.

**Comment by LordFokas** [comment]
Note to the implementor (probably me): Make the QuantumNet avoid setting a source location on the block in that location. This way machines will never request power from themselves, because they don't know they're a source on their network.

**Comment by sammko** [comment]
Finished as of 74dab6a84423d6b8a256d7534f1ac2082eb3a400

**Comment by LordFokas** [comment]
Probably not. Hook 2 capacitors together, feed one of them. Energy will probably loop between them.
They need to be sided.

**Comment by sammko** [comment]
that is ture

**Comment by hunterboerner** [comment]
We need to fix that loop

**Comment by hunterboerner** [comment]
@LordFokas do you know how to fix this?
