### ISSUE TITLE
Location Card metadata in creative mode

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#27]
ItemStack.setItemDamage(int) doesnt seem to work in creative.

**Comment by hunterboerner** [comment]
Why do we need to set the damage at all?

**Comment by sammko** [comment]
For the texture. I didnt manage to get the ItemStack into a method that can change texture. i KNOW there are 2, but they only change the texture of the 3D item in your hand. so i did it with damage.

**Comment by hunterboerner** [comment]
Store it in nbt, whether written or not. I mean, the data itself is already in nbt

**Comment by sammko** [comment]
You cannot get the nbt without the itemstack

**Comment by hunterboerner** [comment]
@sammko 
Could you for now change it over to ItemStack just so it works at least in survival. I will take a look into it in 0.5 or before 1.0

**Comment by sammko** [comment]
what?

**Comment by hunterboerner** [comment]
Can you get it working for at least in survival and we'll deal with
creative later

On Mon, Jul 29, 2013 at 4:30 AM, sammko notifications@github.com wrote:

> what?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QuantumCraft/QuantumCraft/issues/27#issuecomment-21708597
> .

## 

Theron Boerner

## Theronsminecraft.com

**Comment by sammko** [comment]
It works in survival
