### ISSUE TITLE
Packet for QEInjector.

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#28]
PacketHandler doesnt wanna load packets for QEInjector.

**Comment by hunterboerner** [comment]
Are they in the same class as the other init packets?

**Comment by sammko** [comment]
Why don't you look in the code?

**Comment by hunterboerner** [comment]
Will take a look this weekend and hopefully resolve it by Sunday which is 0.3 deadline (moved things apart because we didn't have enough time to get it done.)

**Comment by hunterboerner** [comment]
Nope, packet is being loaded.

**Comment by sammko** [comment]
Oh yeah it works now.. didnt before from some reason..
