### ISSUE TITLE
Textures for QEInejctor

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#29]

**Comment by sammko** [comment]
Ok, i did it myself and i really do like it :D

**Comment by ghost** [comment]
I apologize for re-opening and such, but I won't be able to get on my computer for 1-2 days due to major harddisk issues. Just needed to let you know.

**Comment by hunterboerner** [comment]
You don't need to re-open it.

**Comment by sammko** [comment]
Yep, theres a just comment button

**Comment by ghost** [comment]
Okay
