### ISSUE TITLE
Research System

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#31]
The research system needs to be done by the milestone stated above.

It will have different branches of research which each have their own special function.

see: qc_common/mods/quantumcraft/reserach/tree.txt

EDIT: I think we do not need it functional in 0.5. we will just implement the crafting recipes w/o research.
EDIT2: I am thinking this can be made a secondary feature. it wont be that hard to do when we already have stuff done.

@sammko, I am assigning you so that you can reply about information and that it will contact you, once you are in the system I can assign anyone else. You are also the one who knows what this does.

**Comment by sammko** [comment]
see #104
