### ISSUE TITLE
Quantum Dislocator buggy as HELL

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#34]
http://www.youtube.com/watch?v=iC7jdQ5skSA
take a look.

When 2 chests are linked with the dislocator, one of the chests looses its texture. Also, the chest with no texture is no longer a valid inventory.

example: http://puu.sh/3O6ct.jpg

**Comment by sammko** [comment]
Fixed most of the rendering bugs, however some are still present

**Comment by hunterboerner** [comment]
Chest rotation
Furnace cooking changes the block ID causing it to clear their inventory
Will add more when I findz them

**Comment by sammko** [comment]
Issue #46

**Comment by hunterboerner** [comment]
Moved to 1.0 because _if_ we merge with qcraft they will have something and this ain't important.
