### ISSUE TITLE
Quantum De-Materializer Texture

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#38]
Travis _may_ have gimp.

**Comment by ghost** [comment]
Even if I did, I don't have dropbox.
Plus my computer is going to get fixed the moment all my files are backed up (I got my external harddrive) and when my re-install disk comes in.

**Comment by ghost** [comment]
Plus I don't have anywhere to save my image, as I am using my computer from a flash drive.

**Comment by hunterboerner** [comment]
Partially done
