### ISSUE TITLE
Quantonium Animal

### ISSUE THREAD

**Issue by loudwhisper** [HeisenBugDev/QuantumCraft#40]
what if we had the quantum injector be used on a animal. it would have a 10% chance of working and either turn it into a mutant or a chunk of plutonium. and 90% chance of causing a super explosion. this is only an idea. 

Edit: Changed the name to Quantonium Animal

**Comment by hunterboerner** [comment]
Could you elaborate little bit more on the idea? It's unclear on what you mean.
