### ISSUE TITLE
Debug in config

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#41]
Let's add a debug setting in the config so we don't have to get rid of the println() statements and if it DOES work but breaks eventually, we can easily turn them back on.

**Comment by hunterboerner** [comment]
@sammko did you assign yourself?

**Comment by sammko** [comment]
yeah

**Comment by hunterboerner** [comment]
This is just going to be fun!
:-)

**Comment by hunterboerner** [comment]
This isn't something that's "done" but I got all that we really have for now done.
