### ISSUE TITLE
Build.xml packages buildcraft in it.

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#42]
Fjidsijkljfhksdhfkjdshgkufjl;

**Comment by sammko** [comment]
i dont think this matters, buildcraft doesnt get packaged into the artifact so i think we can leave it there.

**Comment by hunterboerner** [comment]
Incorrect. It _did_ package it. Note that I recently added an exclude in the copy section.

**Comment by sammko** [comment]
oh, well it doesnt anymore :P

**Comment by hunterboerner** [comment]
that's.cause.I.fixed.it

**Comment by hunterboerner** [comment]
God cell phones

**Comment by sammko** [comment]
lol
