### ISSUE TITLE
Location Card Spelling

### ISSUE THREAD

**Issue by thejereman13** [HeisenBugDev/QuantumCraft#43]
The tool-tip on the Location Card has the words "blank" and "block" reversed. It would also be nice to spell out right click instead of abbreviating it.

**Comment by hunterboerner** [comment]
What does it say currently?

On Sun, Jul 28, 2013 at 5:51 PM, thejereman13 notifications@github.comwrote:

> The tool-tip on the Location Card has the words "blank" and "block"
> reversed. It would also be nice to spell out right click instead of
> abbreviating it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QuantumCraft/QuantumCraft/issues/43
> .

## 

Theron Boerner

## Theronsminecraft.com

**Comment by thejereman13** [comment]
"Shift r-click on a block Blank"

**Comment by hunterboerner** [comment]
The blank means that there is no data on it. I'll fix that eventually.

On Sun, Jul 28, 2013 at 5:54 PM, thejereman13 notifications@github.comwrote:

> "Shift r-click on a block Blank"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QuantumCraft/QuantumCraft/issues/43#issuecomment-21692930
> .

## 

Theron Boerner

## Theronsminecraft.com

**Comment by hunterboerner** [comment]
You don't close it until it is fixed -_-
