### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by thejereman13** [HeisenBugDev/QuantumCraft#44]
This is just a suggestion, but it would be nice to add tooltips to the energy bar on your machines saying how much energy is currently stored.

**Comment by hunterboerner** [comment]
Machines don't store energy when in the inventory.

On Sun, Jul 28, 2013 at 5:57 PM, thejereman13 notifications@github.comwrote:

> This is just a suggestion, but it would be nice to add tooltips to the
> energy bar on your machines saying how much energy is currently stored.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QuantumCraft/QuantumCraft/issues/44
> .

## 

Theron Boerner

## Theronsminecraft.com

**Comment by thejereman13** [comment]
I meant the energy bar in the GUI

**Comment by hunterboerner** [comment]
Yes, good idea

**Comment by sammko** [comment]
there isnt really enough space in the gui, unless we manage to get the text to be vertical

**Comment by hunterboerner** [comment]
He means tool tip as in when you hover over the power bar.

**Comment by sammko** [comment]
oooh

**Comment by hunterboerner** [comment]
Reference for how to do this:

https://github.com/calclavia/Modular-Force-Field-System/blob/master/src/mffs/base/GuiMFFS.java

**Comment by sammko** [comment]
this is being fixed with the new guis
