### ISSUE TITLE
qdislocator Texture Error

### ISSUE THREAD

**Issue by thejereman13** [HeisenBugDev/QuantumCraft#46]
When 2 chests are linked with the dislocator, one of the chests looses its texture. Also, the chest with no texture is no longer a valid inventory.

example: http://puu.sh/3O6ct.jpg

**Comment by hunterboerner** [comment]
why is your health and food all over the place?

**Comment by thejereman13** [comment]
It's a mod, I'll find the name and send you a link.

**Comment by hunterboerner** [comment]
Ah, ok

**Comment by hunterboerner** [comment]
Wait what, why would he have a mod installed for writing a mod if it's not needed?

**Comment by sammko** [comment]
what?
i amp pretty sure he is not writing a mod

**Comment by hunterboerner** [comment]
Somewhat duplicate of #34 
This will be added onto that.
