### ISSUE TITLE
Energy Net Source List stuff

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#47]
When you place down an EnergySink and an EnergySource with a gap between, and then put an EnergyComponent in between it doesn update EnergySourceList in the Sink. I could fix this myself but i am afraid i would break it.

**Comment by hunterboerner** [comment]
i would break it too

**Comment by hunterboerner** [comment]
@LordFokas wake up.

**Comment by LordFokas** [comment]
The QuantumEnergyNet class has been fixed. Now it's up to you.
I won't mess with develop, so I don't break your stuff.

**Comment by hunterboerner** [comment]
Updated label

**Comment by hunterboerner** [comment]
fixed in 289e522c90cf2f2407db71756b52ecb105f799ca
