### ISSUE TITLE
Quantum Hoe

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#52]
Travis wants to pimp

**Comment by ghost** [comment]
yes

**Comment by hunterboerner** [comment]
Just yes?

**Comment by ghost** [comment]
yeah

**Comment by ghost** [comment]
this is a good way to fill up inboxes

**Comment by sammko** [comment]
we dont need a hoe.
no hoe.

**Comment by hunterboerner** [comment]
Yeah well he wants to pimp.

**Comment by sammko** [comment]
You know what, i think we can make a hoe that tills 5x5 square of dirt/grass unless its discharged.

**Comment by ghost** [comment]
Thanks c:

**Comment by hunterboerner** [comment]
It's time for @wtg62 to pimp!

**Comment by ghost** [comment]
YOU MADE IT?!
Awesome.
The texture is already done for it. (Was completed months ago)

**Comment by hunterboerner** [comment]
No. I said I want to get you ready to pimp.

On Mon, Nov 25, 2013 at 5:28 PM, wtg62 notifications@github.com wrote:

> YOU MADE IT?!
> Awesome.
> The texture is already done for it. (Was completed months ago)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HeisenBugDev/QuantumCraft/issues/52#issuecomment-29253568
> .

## 

## Theron Boerner

**Comment by hunterboerner** [comment]
@wtg62 I think about 9001 other mods have this. You can go pimp using that hoe.

**Comment by ghost** [comment]
fffuuuuuuuuuu
