### ISSUE TITLE
ItemEnergyUtils not changing damage value

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#59]
We don't need it but it would be nicer if we could use it.

**Comment by hunterboerner** [comment]
@sammko (I just want to get you in the email system)

**Comment by sammko** [comment]
How is it bbroken? It works fine except the damage values

**Comment by hunterboerner** [comment]
I see, since it doesn't render damage you don't know to charge it up and that was why I was confused.

**Comment by sammko** [comment]
If you extend ItemChargable it shows 'QEU: cur/max' on the tooltip

**Comment by hunterboerner** [comment]
I think we aren't using that because we want to just be able to extend something like ItemTool or ItemPickaxe
