### ISSUE TITLE
Why are we setting max damage of 32?

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#61]
Uh why. It seems pointless.

**Comment by hunterboerner** [comment]
I'd rather have the damage display the power level.

**Comment by sammko** [comment]
That's what it is for. If you look at ItemEnergyUtils.set damage, you n see
that it scales down the power level to 0-32

**Comment by sammko** [comment]
Same thing that ic2 does but with a more normal number than 27

**Comment by hunterboerner** [comment]
Either way it seems pointless so I'm removing it.

**Comment by sammko** [comment]
Are you gonna set the maxdamaxe to maxenergyvalue?

**Comment by hunterboerner** [comment]
Yes
