### ISSUE TITLE
QFiberWire needs a TE

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#71]
Right now it is returning null and can crash the game.

**Comment by sammko** [comment]
Why exactly does it need a TE? Our energy system is coded so that you don't really need TEs

**Comment by hunterboerner** [comment]
It crash le game. I will get error report later.

**Comment by sammko** [comment]
we need to fix that, but it definitely doesnt need a TE.

**Comment by LordFokas** [comment]
@hunterboerner where's the report? or is this fixed?

**Comment by hunterboerner** [comment]
Not fixed yet. Haven't gotten to it.

**Comment by hunterboerner** [comment]
Haven't been able to find that problem again and was most likely caused by something else. Closing unless someone reports it again.
