### ISSUE TITLE
REVERT FORGE UPDATE

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#72]
SAMMKO! BUILDCRAFT IS NOT UPDATED. HOW DID YOU NOT GET COMPILER ERRORS LOCALLY. WE CANNOT UPDATE IF OUR DEPENDANCIES DON'T SUPPORT THAT VERSION!

**Comment by sammko** [comment]
BC is updated you dumbass. Just download the zip from their github

**Comment by sammko** [comment]
https://github.com/BuildCraft/BuildCraft/archive/master.zip

**Comment by hunterboerner** [comment]
Not according to thier build script

**Comment by sammko** [comment]
Just DL the zip and stick it in there... it works for me

**Comment by hunterboerner** [comment]
Why did you remove mods.?

**Comment by sammko** [comment]
It looked retarded IMO so I just moved quantumcraft into root

**Comment by hunterboerner** [comment]
#close
