### ISSUE TITLE
Fancy GUIs for everything else

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#76]

**Comment by sammko** [comment]
Yep

**Comment by sammko** [comment]
this will take a long time tho.

**Comment by hunterboerner** [comment]
We need it to be consistent. Constant refactoring for faster developing is
what we're striving for. If we are able to get that correct then we will be
able to add a new GUI almost instantly.

On Thu, Oct 17, 2013 at 2:15 PM, sammko notifications@github.com wrote:

> this will take a long time tho.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HeisenBugDev/QuantumCraft/issues/76#issuecomment-26540070
> .

## 

## Theron Boerner

**Comment by sammko** [comment]
indeed

**Comment by sammko** [comment]
Extractor done. It has the same format as the injector cause it does basically the same thing and the GUI is just about the same. I was thinking about merging them anyways

**Comment by hunterboerner** [comment]
Status update?

**Comment by sammko** [comment]
Closed w/ ce91fd281dd4f2779239229726fdfa319b2f616a
