### ISSUE TITLE
New Unbioxenium (originally plutonium) texture

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#79]

**Comment by sammko** [comment]
i think we can use the same texture.

**Comment by hunterboerner** [comment]
Travis no like it

On Thu, Oct 17, 2013 at 2:14 PM, sammko notifications@github.com wrote:

> i think we can use the same texture.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HeisenBugDev/QuantumCraft/issues/79#issuecomment-26540050
> .

## 

## Theron Boerner
