### ISSUE TITLE
Observer Effect

### ISSUE THREAD

**Issue by LordFokas** [HeisenBugDev/QuantumCraft#82]
Since this is QUANTUM Craft, and we do have machines who perform specific tasks over time, we should have an observer effect, where machines being observed work faster.

Do you want your machine to finish its work urgently? Stare at it.
The same way you do with your torrents, except it works.

( Someone should make a Quantum Torrent Client :P )

Of course, to avoid player entities staring at rooms full of machines while the player is making a toast on the other side of the house, there should be some sort of limitation, like the effect applying only to open GUIs or being close enough to the machine to render the block highlight lines.

But to make it funnier, the more observers the higher the speed increase, limited to a specific per machine cap.

"Hey, get over here, stare at this machine with me!"

**Comment by hunterboerner** [comment]
This will most likely be annoying to use and problematic to code. Unless someone wants to do this themselves (@LordFokas?) then I am closing this.

**Comment by sammko** [comment]
i know it will be problematic to code but who cares? We can do it

**Comment by hunterboerner** [comment]
The problem I see is that it will be highly glitchy as qcraft is already having problems with stuttering.

**Comment by sammko** [comment]
We can make it so that the GUI has to be open for it to run faster. Thats just a few packets and it should work. Maybe even a player count indicator in the GUI

**Comment by hunterboerner** [comment]
Sounds reasonable. Can you do the code part of this: https://github.com/HeisenBugDev/QuantumCraft/issues/134?

**Comment by hunterboerner** [comment]
+1
