### ISSUE TITLE
Quantum De-electrifier texture!

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#84]
Just a texture that goes with the Electrifier's.

**Comment by ghost** [comment]
Huh, I thought I already did this.

**Comment by hunterboerner** [comment]
@wtg62 If you did, then you never sent it.

**Comment by ghost** [comment]
@hunterboerner I have uploaded the new textures. Let me know if you need anything else.

**Comment by hunterboerner** [comment]
Where the hell did you get QED? It's QDL.
