### ISSUE TITLE
Refactor GUI code

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#86]
@sammko, please refactor the code for guiQEInjector and guiBase so that we can add new GUIs using the new system without much repetition.

**Comment by sammko** [comment]
Yeah, I have that planned before adding new GUIs. I think I can manage that this week. The QEI GUI is still missing the upgrade system. (That's what the free space is for)

**Comment by sammko** [comment]
I think we can postpone the new GUIs to a later milestone. The injector one can be a sneakpeek

**Comment by hunterboerner** [comment]
@sammko did you do this?

**Comment by sammko** [comment]
Mostly, but there is one more thing I can do

**Comment by sammko** [comment]
Hmm, forget it

**Comment by hunterboerner** [comment]
Forgot\* and where are the other guis?

**Comment by sammko** [comment]
no forget\* and there are no other GUIs than the extractor yet
