### ISSUE TITLE
oreDictionary implementation

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft#88]
I think the title says it all. If it doesn't, contact me via the comments preferably on this issue.

EDIT: You forgot a comma. That was an important comma.

EDIT: Sorry.

**Comment by hunterboerner** [comment]
Is there a reason we should? Nothing we have is going to be in other mods and is not important right now.

**Comment by sammko** [comment]
You never know
Lets just leave it open

**Comment by hunterboerner** [comment]
simple http://www.minecraftforge.net/wiki/How_to_use_the_ore_dictionary

**Comment by hunterboerner** [comment]
It's in.
