### ISSUE TITLE
Quantum Wormhole Inducer

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#9]
Teleport? (still not planned well, LOW PRIORITY)

**Comment by sammko** [comment]
This could be merged with the computer from qCraft

**Comment by hunterboerner** [comment]
Noap!

**Comment by sammko** [comment]
What is your problem? closing issues like retarded. We will be left with no feature issues. Is that what you want? not add any more features? cause i dont have a problem with getting a new dev

**Comment by hunterboerner** [comment]
"This could be merged with the computer from qCraft"

It's there, we don't need to reinvent the wheel.

**Comment by sammko** [comment]
Yes, but our can do other stuff. teleport entities and a lot of other stuff
